### ISSUE TITLE
Unable to stop sloane.c

### ISSUE THREAD

**Issue by mame** [mame/xterm-pty#29]
When I run sloane.c and press Ctrl+C, it stops once. However, it does not stop when I re-run it and press Ctrl+C again. I would like to look into this over the weekend.

@RReverser I'd like to release xterm-pty 0.9.7 after this is fixed. If there is anything you want to do before release, let me know

**Comment by RReverser** [comment]
> @RReverser I'd like to release xterm-pty 0.9.7 after this is fixed. If there is anything you want to do before release, let me know

Not really, it's been working well for the app I made those changes for and I haven't looked at it since.

That said, given the amount of changes, some of which can be potentially risky, I'd suggest it should be semver-minor not semver-patch - 0.10.0 - so that npm doesn't auto-update to this version for all current consumers.

**Comment by mame** [comment]
I found that this is because `emscripten-pty.js` calls `PTY.onSignal` but not calls its `dispose()`. The second run adds a new hook by calling `PTY.onSignal` additionally, but the older hook remains. When the second run exits, the older hook is executed first and it throws an exception, so the newer hook is not executed.

We need to save the return value of `PTY.onSignal` and call its `dispose()` when the process exits. I don't know how to fix `emscripten-pty.js`. @RReverser Can you take a look?

**Comment by mame** [comment]
I think it is possible to add code at exit by `addAtExit`, but don't know how to keep the value between init and exit.

```
// in initRuntime (added by addAtInit)
saveSignalEventEmitter = PTY.onSignal(...); // How can we keep `saveSignalEventEmitter`?

// in _proc_exit or somethere (by addAtExit)
saveSignalEventEmitter.dispose();
```

**Comment by mame** [comment]
Ah, alternatively, should EventEmitter ignore exceptions in the hook?

**Comment by mame** [comment]
Apparently, `addAtExit` does not work well with `ENVIRONMENT_IS_PTHREAD`. It's out of my hands, so I'll workaround it by doing `openpty` every time the emscripten runtime is started.

However, I think it is never good to have `PTY.onSignal` leaking. I would like @RReverser to take a look when you have the time.

**Comment by RReverser** [comment]
> Apparently, `addAtExit` does not work well with `ENVIRONMENT_IS_PTHREAD`.

Hm that's probably what I'd try too. Why doesn't it work with pthreads?

**Comment by mame** [comment]
Looks like that `exitJS` function throws `'unwind'` before calling `exitRuntime()` when `ENVIRONMENT_IS_PTHREAD`.

https://github.com/emscripten-core/emscripten/blob/72c3be342861765b620ea0d00e192aa2ac19b744/src/library.js#L78-L92

Also, `exitRuntime()` returns without executing `<<< ATEXITS >>>` when `ENVIRONMENT_IS_PTHREAD`.

https://github.com/emscripten-core/emscripten/blob/72c3be342861765b620ea0d00e192aa2ac19b744/src/preamble.js#L275

I'm not sure because the code is complicated, but it does not seem to support `exit` when `ENVIRONMENT_IS_PTHREAD`.

**Comment by RReverser** [comment]
> Also, exitRuntime() returns without executing <<< ATEXITS >>> when ENVIRONMENT_IS_PTHREAD.

Right, this is expected - you don't want to run those in the proxied thread (in a Worker), but rather on main one that ran the `addOnInit` JS. Otherwise there would be a mismatch.

> Looks like that exitJS function throws 'unwind' before calling exitRuntime() when ENVIRONMENT_IS_PTHREAD.

It performs `exitOnMainThread` before that, which should send an exit request back to the main thread, and then I think the main thread should still exit properly, running those handlers... at least that's what I would expect looking at the linked code, but maybe there's some deeper limitation in Emscripten and it doesn't for `PROXY_TO_PTHREAD` mode?

**Comment by mame** [comment]
To be honest, I haven't followed the proxy structure. It's too complicated to me ;-)

All I saw is that I added `console.log` with `addAtExit` and it didn't print the log. I did add `-s EXIT_RUNTIME`.

I think I'm missing something, but I don't know what to do.
