### ISSUE TITLE
How do I capture keypresses?

### ISSUE THREAD

**Issue by kjvalencik** [mame/xterm-pty#8]
I'm able to catch keypresses on the terminal, but even if I try to stop propagation, they still make their way into `xterm-pty`.

I would like to add some hooks for things like arrow keys. Any suggestions? Thanks!

```js
xterm.onKey(e => {
    e.preventDefault();
    e.stopPropagation();
});
```

**Comment by mame** [comment]
I think it would be better for you to ask the xterm.js authors how to suppress event notifications to addons. I don't think that it would make sense for every addon like xterm-pty to provide such a hook.

If there is something wrong with xterm-pty as xterm.js addon in terms of event handling, I will be happy to fix it.

Note that xterm-pty uses `onData` and `onBinary` instead of `onKey`.
